spring:
  application.name: authorization-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: google-client
          github:
            provider: github
            clientId: ${GITHUB_ID}
            clientSecret: ${GITHUB_SECRET}
            scope: user:email, read:user
            client-name: github-client
        provider:
#          google.user-name-attribute: email
          github.user-name-attribute: login
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "https://oauthdebugger.com/debug"
#              post-logout-redirect-uris:
#                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            token:
              access-token-time-to-live: 30m
              refresh-token-time-to-live: 1d
              reuse-refresh-tokens: true

server:
  port: 8080